blacklist:
    hg19: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/hg19_blacklist_merged.bed
    mm10: /nfs/med-bfx-activeprojects/Ryan_rjhryan_CU1/mm10_blacklist_merged.bed

bwa_index:
    hg19 : /nfs/turbo/epicore-active/genomes/Homo_sapiens/UCSC/hg19/Sequence/BWAIndex/genome.fa
    mm10 : /nfs/turbo/epicore-active/genomes/Mus_musculus/UCSC/mm10/Sequence/BWAIndex/genome.fa

chrom_sizes:
    hg19: /nfs/turbo/epicore-active/genomes/Homo_sapiens/UCSC/hg19/hg19.chrom.sizes
    mm10: /nfs/turbo/epicore-active/genomes/Mus_musculus/UCSC/mm10/mm10.chrom.sizes

tss:
    hg19: /nfs/turbo/epicore-active/rcavalca/repos/develop/Orochi_atac/data/hg19_tss.bed
    mm10: /nfs/turbo/epicore-active/rcavalca/repos/develop/Orochi_atac/data/mm10_tss.bed

deeptools_bamcoverage_params: "--binSize 25 --normalizeUsing CPM --extendReads"
samtools_prune_flags: "-f 0x1 -f 0x2 -F 0x4 -F 0x8 -F 0x100 -F 0x400 -F 0x800"
