blacklist:
    hg19: /nfs/turbo/path-rjhryan-turbo/data-public/reference_annotations/hg19/wgEncodeHg19ConsensusSignalArtifactRegions.bed
    mm10: /nfs/turbo/path-rjhryan-turbo/data-public/reference_annotations/mm10/mm10.blacklist.bed

bwa_index:
    hg19: /nfs/turbo/path-rjhryan-turbo/software/bwa_indexes/hg19
    mm10: /nfs/turbo/path-rjhryan-turbo/software/bwa_indexes/mm10

chrom_sizes:
    hg19: /nfs/turbo/path-rjhryan-turbo/data-public/reference_genomes/hg19.chromsizes
    mm10: /nfs/turbo/path-rjhryan-turbo/data-public/reference_genomes/mm10.chromsizes

deeptools_bamcoverage_params: "--binSize 25 --normalizeUsing CPM --extendReads 150"
samtools_prune_flags: "-F 0x4 -F 0x100 -F 0x200 -F 0x400 -F 0x800"
igvtools_count_params: "--includeDuplicates"
makeTagDir_params: "-keepAll -checkGC"
homer_findPeaks_params: "-style factor"
homer_fmg_params: "-bits -preparsedDir /scratch/rjhryan_root/rjhryan/trsaari/tmp/"
